name: config_props_extractor
description: A command-line application to get properties from ConfigMaps and Secrets
version: 1.4.2-rc1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0
# Add regular dependencies here.
dependencies:
  clock: ^1.1.1
  dotenv: ^4.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  path: ^1.8.3
  process_run: ^0.13.0
  yaml_magic: ^1.0.5
dev_dependencies:
  fake_async: ^1.3.1
  lints: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.21.0
